### ISSUE TITLE
The Ui is not opening.

### ISSUE THREAD

**Issue by MadManDanCat** [morethancodenl/mtc-cityhall#1]
The UI will not open at all... I have tried to changed the target function too and still no success.  There are no errors console or server side either.

exports['qb-target']:AddBoxZone("Cityhall", vector3(-552.05, -189.47, 38.22), 0.5, 0.5, { name="City Hall Menu", heading =30.0, debugPoly=false, minZ=37.0, maxZ=39.0 }, 
{ options = { { event = "mtc-cityhall:client:open", icon = "fas fa-user-check", label = "Open City Hall"}, },
  distance = 3.0
})

**Comment by NietThijmen** [comment]
Are you running the latest version of the script?

**Comment by MadManDanCat** [comment]
> Are you running the latest version of the script?

Yes I installed the latest version.

**Comment by NietThijmen** [comment]
does the UI open with the integrated ped spawner?

**Comment by MadManDanCat** [comment]
No it does not it doesn't work at all.

**Comment by Mitchel** [comment]
@MadManDanCat is it possible for you to make a clip of your problem? And possibly also share a little more code with us? You can also do this through our Discord if necessary if it feels more comfortable for you. Otherwise, a response to this is always fine. Myself, as well as several other users are currently only reporting to us that it works. So unfortunately we cannot reproduce your problem in our own environment.

**Comment by Manliketjb** [comment]
Same issues here, Target zone gets detected but the UI it self doesn't open. Changed the zone to all the different types, Set it up as a E prompt and even a command and neither opens the UI

**Comment by NietThijmen** [comment]
Can you maybe send a clip & your code in a ticket?
